// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLC0ZgAIGBv41PvghNleRQHBHMho7UNhI',
    appId: '1:696586000488:web:bfb1ad9ee23e87493c03dd',
    messagingSenderId: '696586000488',
    projectId: 'gl-b294b',
    authDomain: 'gl-b294b.firebaseapp.com',
    storageBucket: 'gl-b294b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD-KYJ32RettGgeODnWFE5MMcfTz6hlGI',
    appId: '1:696586000488:android:fd0414d4393749d33c03dd',
    messagingSenderId: '696586000488',
    projectId: 'gl-b294b',
    storageBucket: 'gl-b294b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4UJaiJeniS4pMsnCKJSgwWdQ64X0i_ME',
    appId: '1:696586000488:ios:8bbe5611973313543c03dd',
    messagingSenderId: '696586000488',
    projectId: 'gl-b294b',
    storageBucket: 'gl-b294b.firebasestorage.app',
    iosBundleId: 'com.example.glamazon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4UJaiJeniS4pMsnCKJSgwWdQ64X0i_ME',
    appId: '1:696586000488:ios:8bbe5611973313543c03dd',
    messagingSenderId: '696586000488',
    projectId: 'gl-b294b',
    storageBucket: 'gl-b294b.firebasestorage.app',
    iosBundleId: 'com.example.glamazon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLC0ZgAIGBv41PvghNleRQHBHMho7UNhI',
    appId: '1:696586000488:web:c5664d12ec27f0843c03dd',
    messagingSenderId: '696586000488',
    projectId: 'gl-b294b',
    authDomain: 'gl-b294b.firebaseapp.com',
    storageBucket: 'gl-b294b.firebasestorage.app',
  );
}
